apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: align-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: align.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: align-backend-svc
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: align-frontend-svc
                port:
                  number: 3000
