apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: align-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - align.example.com
      secretName: align-tls-cert
  rules:
    - host: align.example.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: align-backend-svc
                port:
                  number: 8000
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: align-frontend-svc
                port:
                  number: 3000
